apiVersion: v1
kind: Service
metadata:
  name: goserver-service
spec:
  selector:
    app: goserver
  type: NodePort
  ports:
  - name: goserver-service-port
    port: 8081
    targetPort: 8081
    protocol: TCP
    nodePort: 30001 #A porta precisa estar entre 30000 e 32767
